### ISSUE TITLE
Sorry it is not yet available on mobile

### ISSUE THREAD

**Issue by popcorn2024ok** [mohdje/medflix#5]
![IMG_0935](https://github.com/mohdje/medflix/assets/165403113/b6561fb6-7732-4890-948d-ae42ed093a3a)

does not work for mobile and other devices with ipad and iphone android mobile android tv safari chrome browser

Sorry it is not yet available on mobile

**Comment by Doctor2023** [comment]
I have the same problem too

**Comment by mohdje** [comment]
Medflix is only available on desktop for Windows and MacOs. There is also a docker image if you want to host it in a docker container and access it with a web browser. Look at the release section for more info.
